# Notebook 08 - File Input/Output

### open

file_in = open(path,mode)

where path is a string with the path to the file

'filename.txt'

or '/users/jdolen/Documents/filename.txt' 


and mode is a string which sets access:

'r' : use for reading

'w' : use for writing

'x' : use for creating and writing to a new file

'a' : use for appending to a file

'r+' : use for reading and writing to the same file

### Writing

In [2]:
# First open a new file
path = 'candy3.txt'
file = open(path,'x')

In [3]:
# now that the new file is open, we can write to it:
file.write("Snickers")
file.write("Twix")
file.write("KitKat")

6

In [4]:
# if you are done you should close the file
file.close()

In [5]:
# On a linux or mac computer this command will show you the contents of candy.txt
! head candy2.txt

# On a windows computer you can try opening the file with windows explorer

SnickersTwixKitKat

In [6]:
# try again. but note since we are using mode x we can't write to the same file name
path = 'candy.txt'
file = open(path,'x')

FileExistsError: [Errno 17] File exists: 'candy.txt'

In [6]:
# we can write over the previous file with mode w (be careful!)
path = 'candy.txt'
file = open(path,'w')

In [7]:
! head candy.txt

In [8]:
# we need to be explicit with our new lines etc.:
file.write("Snickers\n")
file.write("Twix\n")
file.write("KitKat\n")
file.close()

In [9]:
! head candy.txt

Snickers
Twix
KitKat


In [11]:
# reopen the file and write more
path = 'candy.txt'
file = open(path,'a')
file.write("Almond Joy\n")
file.close()

In [12]:
! head candy.txt

Snickers
Twix
KitKat
Almond Joy


In [13]:
# now lets read the file
openfile = open(path,'r')

In [14]:
openfile.readline()

'Snickers\n'

In [15]:
openfile.readline()

'Twix\n'

In [16]:
openfile.readline()

'KitKat\n'

In [22]:
openfile.readline()

'Almond Joy\n'

In [23]:
openfile.readline()

''

In [24]:
openfile.close()

In [25]:
openfile = open(path,'r')
openfile.readlines()

['Snickers\n', 'Twix\n', 'KitKat\n', 'Almond Joy\n']

# Numpy tools

In [26]:
import numpy as np
data = np.random.randn(100, 3)

In [27]:
data

array([[-0.33694416, -0.2321852 ,  0.73272634],
       [ 1.28333933,  0.09769118,  0.26826408],
       [ 0.95179228, -0.63473531,  0.77753847],
       [-0.29106342,  0.51356453,  0.18090896],
       [-1.13230135,  0.96475806,  1.1679287 ],
       [ 0.37600284,  1.02473407, -0.28972875],
       [-0.12398637, -0.88106554, -0.03236838],
       [ 0.55671396, -0.3062148 , -0.4853389 ],
       [ 0.70551991,  0.66069465,  0.25556418],
       [ 0.01700096, -0.14348311,  0.31073241],
       [ 0.23604134, -0.5473076 ,  0.7491704 ],
       [ 1.28767838, -2.34324807, -0.05068965],
       [ 1.64270046,  0.6174843 ,  0.20245567],
       [ 0.13894578,  0.85166463, -1.41428592],
       [ 0.10912024,  0.06446715, -0.61634612],
       [ 0.94933793, -1.94738006, -1.47187523],
       [ 0.31375776,  0.09032242, -1.30800142],
       [-0.22981505, -1.16174058,  1.46226689],
       [ 0.11767741, -0.12423938,  0.67931334],
       [-2.37090656,  0.20835512, -1.65548796],
       [ 1.0074471 ,  0.3984926 , -0.390

In [28]:
# Numpy savetxt tool
np.savetxt("data.csv", data, delimiter=",", header="x,y,z", comments="# Random x, y, z coordinates\n")

In [29]:
!head data.csv

# Random x, y, z coordinates
x,y,z
-3.369441605294868913e-01,-2.321851992971336598e-01,7.327263380207629240e-01
1.283339330551183766e+00,9.769117566894519600e-02,2.682640799130707743e-01
9.517922760667272275e-01,-6.347353084779719934e-01,7.775384715967080806e-01
-2.910634202495309686e-01,5.135645281449582322e-01,1.809089628770913227e-01
-1.132301354443359775e+00,9.647580565414213272e-01,1.167928696355872598e+00
3.760028386017330027e-01,1.024734067868779519e+00,-2.897287543331412141e-01
-1.239863723004851065e-01,-8.810655360105564826e-01,-3.236837834172431178e-02
5.567139604623697613e-01,-3.062147985461022848e-01,-4.853388960429744214e-01


In [30]:
data_load = np.loadtxt("data.csv", skiprows=2, delimiter=",")

In [31]:
data[0]

array([-0.33694416, -0.2321852 ,  0.73272634])

In [32]:
data_load[0]

array([-0.33694416, -0.2321852 ,  0.73272634])

# JavaScript Object Notation (JSON)

Open standard fileformat. Human readable and used in many places on the web.

{"name": "George", "age": 50, "Height": 63, "Weight": 190, "IsMarried":true}

Example from CMS:

{"273158": [[1, 1279]], "273302": [[1, 459]], "273402": [[100, 292]], "273403": [[1, 53]], "273404": [[1, 18]], "273405": [[1, 25]], "273406": [[1, 112]], "273408": [[1, 6]], "273409": [[1, 309]], "273410": [[1, 90]], "273411": [[1, 29]], "273425": [[62, 352], [354, 733]], "273446": [[1, 33]], "273447": [[1, 113], [115, 412]], "273448": [[1, 391]], "273449": [[1, 214]], "273450": [[1, 214], [219, 647]], "273492": [[71, 71], [73, 282], [284, 325], [327, 338]], "273493": [[1, 233]], "273494": [[1, 192]], "273502": [[73, 256], [258, 318], [320, 813], [815, 1064]], "273503": [[1, 598]], "273554": [[77, 437]], "273555": [[1, 173]], "273725": [[83, 252], [254, 2545]], "273728": [[1, 100]], "273730": [[1, 1814], [1820, 2126]]}

Translation example:
 "273450": [[1, 214], [219, 647]],
 
 For run 273450 (a period in which the experiment was taking data) the data which has been certified is in lumisections 1-214 and 219-647).



This looks a lot like python dictionary, and the built-in python json encoder/decoder can parse a json file and turn it into a dictionary or vice versa
https://docs.python.org/3/library/json.html

Some nice JSON examples:
http://adobe.github.io/Spry/samples/data_region/JSONDataSetSample.html

In [2]:
import json

In [3]:
json_string = '{"name":"George", "age": 50, "Height": 63, "Weight": 190, "IsMarried":true, "Preferences": [5,28] }'

In [4]:
# Parse the JSON (Decode) and turn it into a dictionary using json.loads
json_parsed = json.loads(json_string)

In [5]:
type(json_parsed)

dict

In [6]:
json_parsed

{'name': 'George',
 'age': 50,
 'Height': 63,
 'Weight': 190,
 'IsMarried': True,
 'Preferences': [5, 28]}

In [7]:
json_parsed["name"]

'George'

In [8]:
json_parsed["Weight"]

190

In [9]:
json_parsed["IsMarried"]

True

In [10]:
type(json_parsed["IsMarried"])

bool

In [11]:
json_parsed["Preferences"]

[5, 28]

In [12]:
type(json_parsed["Preferences"])

list

In [13]:
# Convert a python dictionary into a JSON string
# json.dumps (dictionary->json)
python_dictionary = {'name':'George', 'age':50, 'IsMarried':True, 'Weight': 190}
json_new = json.dumps(python_dictionary)

In [14]:
print(json_new)

{"name": "George", "age": 50, "IsMarried": true, "Weight": 190}


In [15]:
type(json_new)

str

# Hierarchical Data Format (HDF5) 

python libraries which can handle HDF5 files: "h5py" and "PyTables"

HDF5 is not unique to python but these libraries provide a nice interface

## h5py

In [16]:
import h5py
import numpy as np

In [17]:
# CREATE A NEW FILE
#    r  Readonly, file must exist
#    r+ Read/write, file must exist
#    w  Create file, truncate if exists
#    w- or x Create file, fail if exists
#    a  Read/write if exists, create otherwise (default)
f = h5py.File("testfile4.hdf5", "x")

In [18]:
f.mode

'r+'

### "HDF5 Dataset"
* A collection of data elements (similar to NumPy arrays)(you can use slicing)
* immutable (they can't be changed)
* They support storage features such as compression, error detection, and chunked I/O

http://docs.h5py.org/en/latest/high/dataset.html

In [19]:
# object_name = file_name.create_dataset(
#        "data_set_name", 
#        shape (just like numpy arrays - tuple with sets the array dimensions)
#        dtype (datatype) (default value = float)
#      ) 

dset = f.create_dataset("example_dataset", (100,), dtype='i')

In [20]:
dset.shape

(100,)

In [21]:
dset.dtype

dtype('int32')

In [22]:
# set the dataset entries equal to a numpy array
#   note the ... syntax (ellipsis) 
#     -> select any unspecified entries
dset[...] = np.arange(100)  

In [23]:
dset[0]

0

In [24]:
dset[10]

10

In [25]:
dset[0:100:10]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=int32)

### "HDF5 Group"

A group is a containter used to organize HDF5 files. Within python thay are somewhat like dictionaries (they have "keys" and "values")

When we created a file earlier we also created a the "root group". This is similar to the root directory on your computer.

Every object in an HDF5 file has a name and they are accessible through a typical file format hierarchy ("/root/stuff1/stuff1a/etc.")

In [26]:
f.name

'/'

In [27]:
f.keys()

<KeysViewHDF5 ['example_dataset']>

In [28]:
# create a new group
grp = f.create_group("GroupA")

In [29]:
grp.name

'/GroupA'

In [30]:
grp2 = f.create_group("GroupB")
grp2.name

'/GroupB'

In [31]:
subgrp = grp.create_group("GroupA1")

In [32]:
subgrp.name

'/GroupA/GroupA1'

In [33]:
subsubgrp = subgrp.create_group("GroupA1a")

In [34]:
subsubgrp.name

'/GroupA/GroupA1/GroupA1a'

In [35]:
subsubgrp1 = f.create_group("/GroupA/GroupA1/GroupA1b")

In [36]:
subsubgrp1.name

'/GroupA/GroupA1/GroupA1b'

### Combining groups and datasets

In [37]:
dset2 = grp.create_dataset("dataset_two", (50,), dtype='f')
dset2.name

'/GroupA/dataset_two'

In [38]:
dset3 = f.create_dataset('GroupA/GroupA1/dataset_three', (10,), dtype='i')
dset3.name

'/GroupA/GroupA1/dataset_three'

In [39]:
dset3[...] = np.arange(10)  

In [40]:
# Iterate over the direct group members (no sudirectories)
for name in f:
    print(name)

GroupA
GroupB
example_dataset


In [41]:
for name in grp:
    print(name)

GroupA1
dataset_two


In [42]:
for name in subgrp:
    print(name)

GroupA1a
GroupA1b
dataset_three


In [43]:
def printfunc(name):
   print(name)

In [44]:
f.visit(printfunc)

GroupA
GroupA/GroupA1
GroupA/GroupA1/GroupA1a
GroupA/GroupA1/GroupA1b
GroupA/GroupA1/dataset_three
GroupA/dataset_two
GroupB
example_dataset


In [45]:
# lambda function is a one line funcition with no name 
#   Normal python function
#    def function_name(x):
#     return x**2
#   Lambda function 
#    lambda x: x**2
f.visit(lambda x: print(x))

GroupA
GroupA/GroupA1
GroupA/GroupA1/GroupA1a
GroupA/GroupA1/GroupA1b
GroupA/GroupA1/dataset_three
GroupA/dataset_two
GroupB
example_dataset


In [46]:
# you can access data with a dictionary type syntax
type(f["GroupA/GroupA1/dataset_three"])

h5py._hl.dataset.Dataset

In [47]:
type(f["GroupA/GroupA1/GroupA1a"])

h5py._hl.group.Group

In [48]:
datanow = f["GroupA/GroupA1/dataset_three"]

In [49]:
datanow[4]

4

In [50]:
list(f.keys())

['GroupA', 'GroupB', 'example_dataset']

In [51]:
list(f.items())

[('GroupA', <HDF5 group "/GroupA" (2 members)>),
 ('GroupB', <HDF5 group "/GroupB" (0 members)>),
 ('example_dataset',
  <HDF5 dataset "example_dataset": shape (100,), type "<i4">)]

### Attributes

Attach metadata to each dataset

In [52]:
dset3.attrs

<Attributes of HDF5 object at 140220148271280>

In [53]:
dset3.attrs['measurement'] = 'temperature'

In [54]:
dset3.attrs['unit'] = 'celsius'

In [55]:
list(dset3.attrs.keys())

['measurement', 'unit']

## Another method to work with HDF5 files with python: PyTables


open_file

r  Read-only—no data can be modified.

w Write—a new file is created; if a file with that name exists, it is deleted.

a Append—an existing file is opened for reading and writing, or if the file does not exist, it is created.

r+ Similar to a, but the file must already exist.

In [56]:
import tables as tb
ft = tb.open_file('mypytable3', 'a')

In [57]:
ft.root #different than h5py

/ (RootGroup) ''
  children := []

In [58]:
ft.create_group('/', 'GroupA', "My Group A")

/GroupA (Group) 'My Group A'
  children := []

In [59]:
ft.root.GroupA

/GroupA (Group) 'My Group A'
  children := []

In [60]:
# specialized array and table functions for datasets
# http://www.pytables.org/usersguide/libref/homogenous_storage.html
ft.create_array('/GroupA', 'CompetitorNumbers', [1, 2, 5, 3])

/GroupA/CompetitorNumbers (Array(4,)) ''
  atom := Int64Atom(shape=(), dflt=0)
  maindim := 0
  flavor := 'python'
  byteorder := 'little'
  chunkshape := None

In [61]:
myarray = np.random.rand(7)
ft.create_array('/GroupA', 'Time', myarray)

/GroupA/Time (Array(7,)) ''
  atom := Float64Atom(shape=(), dflt=0.0)
  maindim := 0
  flavor := 'numpy'
  byteorder := 'little'
  chunkshape := None

In [62]:
# Get the data from the file
ft.root.GroupA.CompetitorNumbers[:]

[1, 2, 5, 3]

In [63]:
type(ft.root.GroupA.CompetitorNumbers[:])

list

In [64]:
type(ft.root.GroupA.CompetitorNumbers)

tables.array.Array

In [65]:
ft.root.GroupA.Time[:]

array([0.62210425, 0.53811571, 0.01725738, 0.03681912, 0.11785259,
       0.96287604, 0.24506062])

In [66]:
#datatype is preserved
type(ft.root.GroupA.Time[:])

numpy.ndarray

In [67]:
type(ft.root.GroupA.Time)

tables.array.Array

Note: You need to slice the data in order to use it. We have created a hdf5 file which lives on disk. In order to access the stored data you need to slice the dataset such that you move the data to local memory. hdf5 alllow you to use much bigger datasets than standalone numpy.

# Pickle

In [68]:
mydata = {"name":"George", "age": 50, "Height": 63, "Weight": 190, "IsMarried":True, "Preferences": [5,28] }

In [69]:
type(mydata)

dict

In [70]:
mydata

{'name': 'George',
 'age': 50,
 'Height': 63,
 'Weight': 190,
 'IsMarried': True,
 'Preferences': [5, 28]}

In [71]:
import pickle

In [72]:
# save this dictionary in a pickle file
pickle.dump( mydata, open( "mypicklefile.p", "wb" ) )

In [73]:
!head mypicklefile.p

��V}�(�name��George��age�K2�Height�K?�Weight�K��	IsMarried���Preferences�]�(KKeu.

The data in this dictionary (which we could be much more complex than this example) has been converted into some byte stream (the dictionary has been "pickled" (ie. "serialized" or "flattened")

In [74]:
# read a pickle (unpickle the data)
getthedata = pickle.load( open( "mypicklefile.p", "rb" ) )

In [75]:
type(getthedata)

dict

In [76]:
getthedata

{'name': 'George',
 'age': 50,
 'Height': 63,
 'Weight': 190,
 'IsMarried': True,
 'Preferences': [5, 28]}

Instead of storing the data in a file, pickle converts python objects into serial data which can be saved in a file.

In [77]:
def square(x):
    return x*x

In [78]:
square(3)

9

In [79]:
pickle.dump( square, open( "mypicklefile2.p", "wb" ) )

In [80]:
getthedata2 = pickle.load( open( "mypicklefile2.p", "rb" ) )

In [81]:
getthedata2(4)

16

In [82]:
type(getthedata2)

function

You can save functions or other objects and send them along with your data to a colleague.

# One more file format: ROOT (pyROOT)

We won't spend time on this now, but some fields require a more nested file format (a "tree" format)

https://root.cern/manual/root_files/

https://root.cern/manual/trees/

Interesting discussion on why ROOT developed separately:

https://www.youtube.com/watch?v=mB4Chl0ly-g

https://www.youtube.com/watch?v=jvt4v2LTGK0
